#! /bin/sh
# /etc/init.d/neo_pi

### BEGIN INIT INFO
# Provides:          office_indicator
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# I got this example from: http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting neopi"
    # run application you want to start
    ~pi/neo_pi/run_display.py -b 0.1 &
    ;;
  stop)
    echo "Stopping neopoi"
    # kill application you want to stop
    killall run_display.py
    ;;
  *)
    echo "Usage: /etc/init.d/office_indicator {start|stop}"
    exit 1
    ;;
esac

exit 0
